### ISSUE TITLE
Update to php 8.0.1

### ISSUE THREAD

**Issue by taliptako** [devilbox/docker-php-fpm-8.0#13]
Can you update to php 8.0.1 ?

**Comment by fibis** [comment]
@taliptako why did you close this issue?

**Comment by taliptako** [comment]
@fibis Because there is a php 8.0.1 version already in `devilbox/php-fpm:8.0-work-0.123` what we need is 8.0.2 now @cytopia

**Comment by neradp** [comment]
What about latest 8.0.5 version ?
