### ISSUE TITLE
Laravel missing from container

### ISSUE THREAD

**Issue by lokinz** [devilbox/docker-php-fpm-8.0#15]
Setting PHP level to 8.0 in the .env file pulls in `devilbox/php-fpm:8.0-work-0.127`

When I shell into the PHP container and try to run `laravel` I get the `bash: laravel: command not found` error.
This works fine on the 7.4 container. 

Other tools (like symfony) work fine.

**Comment by tiagoflsouza** [comment]
Try:
Take the first step from https://devilbox.readthedocs.io/en/latest/examples/setup-laravel.html
Then run `composer global require laravel/installer` (at devilbox@php-8.0.3 in /shared/httpd)
Finally, just follow the other steps of the link.

**Comment by lokinz** [comment]
Thanks for taking the time to reply.

I am pointing out that the CLI tool is missing from the container whereas it is pre-installed in the others.

**Comment by cytopia** [comment]
@lokinz this is only the base container with no tools installed. Please refer to: https://github.com/devilbox/docker-php-fpm which contains different flavours including desired tools. If it is not available over there, please open an issue at this repository.
